spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.199.100:3306/genki_basic?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: genki-mysql-psd
  aop:
    proxy-target-class: true
  application:
    name: genki-basic-pos
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 47.95.121.120
    port: 6379
    password: 1q2w3e~~
    timeout: 10000
    database: 5
    pool:
      max-active: 20
      min-idle: 2
      max-idle: 10
logging:
  config: classpath:logback-dev.xml
  level:
    com:
      netflix: warn
      onway: debug
    org:
      springframework: info
server:
  port: 9822
  servlet-path: /genki/
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: ./logs
      pattern: "%{X-Forwarded-For}i %a %{X-B3-TraceId}i %t %m %U %s %b %D"
      rename-on-rotate: true
      suffix: .log
      prefix: access
      rotate: true
      buffered: false
      file-date-format: yyyy-MM-dd
mybatis:
  mapper-locations: classpath:cn/teamar/genki/basic/dao/**/*.xml
  type-aliases-package: cn.teamar.genki.basic.dao
  config-location: classpath:mybatis-config.xml
#admin
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.199.100:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      management.context-path: ${server.servlet-path}
    health-check-url-path: ${server.servlet-path}/health

#graceful quit
endpoints:
  shutdown:
    enabled: true
    sensitive: false
#rpc retry
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 25000
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 1000
  #false to only allow get method to retry
  OkToRetryOnAllOperations: true
    # Max number of next servers to retry (excluding the first server)
  MaxAutoRetriesNextServer: 2
    # Max number of retries on the same server (excluding the first try)
  MaxAutoRetries: 0
    # Interval to refresh the server list from the source
  ServerListRefreshInterval: 20000
  retryableStatusCodes: 404,500
# common configs
genki:
  basic:
    cors:
      enable: false
    cache:
      enable: true
      defaultExpire: 86400
      caches:
        - name: user
          expire: 86400
        - name: power
          expire: 3600
      dict:
        power:
          enable: false
    swagger:
      enable: true
    enable-default-captcha: true
    default-captcha: 1234
service:
  genki-food-business:
    name: genki-food-service-dev
    path: /genki
  genki-manager-business: genki-manager-business-pangjie
  eos-core-business:
    name: genki-basic
    path: /basic/rpc/user